version: '3.5'

volumes:
    shaarli-cache:
        external: true
        name: shaarli-cache
    shaarli-data:
        external: true
        name: shaarli-data

services:
    shaarli:
        image: shaarli/shaarli:latest
        ports:
            - 127.0.0.1:8753:80
        volumes:
            - shaarli-cache:/var/www/shaarli/cache
            - shaarli-data:/var/www/shaarli/data
