version: '3'

services:
    kms:
        image: pykmsorg/py-kms:latest
        ports:
            - 0.0.0.0:1688:1688
        environment:
            - IP=0.0.0.0
            - HWID=RANDOM
        volumes:
            - /etc/localtime:/etc/localtime:ro
